// Build the app icons from one source of truth.
//
// The repo logo is a bare line mark on transparency, which is right on a web
// page and wrong in a Dock: macOS sits every icon on the same squircle, so a
// transparent glyph reads as a hole between its neighbours. This script keeps
// the mark and puts it on Troy's own dark plate, then renders the sizes each
// platform wants.
//
//   node scripts/icons.mjs
//
// Output (all generated, none hand-edited):
//   build/icon.png        1024, the master electron-builder converts from
//   build/icon.icns       macOS bundle and DMG
//   build/icons/*.png     Linux, and the window icon on Windows in dev
//
// Windows .ico is generated by electron-builder from build/icon.png at pack
// time, so no image toolchain beyond rsvg-convert is needed to release.
//
// The output is committed rather than built on demand. A Windows runner has
// no rsvg-convert and only macOS has iconutil, so a release that generated
// its own icons could not produce all three platforms. Run this by hand when
// the mark changes, and commit what it writes.

import { mkdir, writeFile, rm, readFile } from 'node:fs/promises'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const run = promisify(execFile)
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const build = path.join(root, 'build')

const PLATE = '#1a1c1e'
const MARK = '#d97757'

/**
 * The icon at any size, as SVG. A 1024 canvas with the mark inset to 62% is
 * close to Apple's own optical sizing, and the 22.37% corner radius is the
 * squircle ratio macOS uses, so Troy lines up with the icons beside it.
 */
function iconSvg() {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">
  <rect x="0" y="0" width="1024" height="1024" rx="229" ry="229" fill="${PLATE}"/>
  <g transform="translate(192 192) scale(20)">
    <g fill="none" stroke="${MARK}" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">
      <path d="M2.4 10.6 V2.4 H10.6"/>
      <path d="M29.6 21.4 V29.6 H21.4"/>
      <circle cx="16" cy="16" r="9.4"/>
      <path d="M16 12 L24.14 11.3"/>
      <path d="M12.54 18 L7.86 11.3"/>
      <path d="M19.46 18 L16 25.4"/>
    </g>
    <path d="M16 12 L19.46 18 H12.54 Z" fill="${MARK}"/>
  </g>
</svg>
`
}

/** Sizes Linux and the dev-mode window icon want. */
const PNG_SIZES = [16, 24, 32, 48, 64, 128, 256, 512, 1024]

/** name and pixel size for each entry macOS expects in an iconset. */
const ICONSET = [
  ['icon_16x16', 16],
  ['icon_16x16@2x', 32],
  ['icon_32x32', 32],
  ['icon_32x32@2x', 64],
  ['icon_128x128', 128],
  ['icon_128x128@2x', 256],
  ['icon_256x256', 256],
  ['icon_256x256@2x', 512],
  ['icon_512x512', 512],
  ['icon_512x512@2x', 1024],
]

async function png(svgPath, size, outPath) {
  await run('rsvg-convert', ['-w', String(size), '-h', String(size), svgPath, '-o', outPath])
}

async function main() {
  await mkdir(build, { recursive: true })
  await mkdir(path.join(build, 'icons'), { recursive: true })

  const svgPath = path.join(build, 'icon.svg')
  await writeFile(svgPath, iconSvg())

  await png(svgPath, 1024, path.join(build, 'icon.png'))
  for (const size of PNG_SIZES) {
    await png(svgPath, size, path.join(build, 'icons', `${size}x${size}.png`))
  }

  if (process.platform === 'darwin') {
    const iconset = path.join(build, 'icon.iconset')
    await rm(iconset, { recursive: true, force: true })
    await mkdir(iconset, { recursive: true })
    for (const [name, size] of ICONSET) {
      await png(svgPath, size, path.join(iconset, `${name}.png`))
    }
    await run('iconutil', ['-c', 'icns', iconset, '-o', path.join(build, 'icon.icns')])
    await rm(iconset, { recursive: true, force: true })
  }

  const master = await readFile(path.join(build, 'icon.png'))
  console.log(`build/icon.png ${master.length} bytes, ${PNG_SIZES.length} sizes in build/icons/`)
  if (process.platform === 'darwin') console.log('build/icon.icns written')
}

await main()
